FROM python:3.10
COPY . /app
WORKDIR /app
RUN apt-get update && apt-get install -y vim \
    && pip install -r requirements.txt
ENV FILE_ID="1ig2ngoXFTxP5Pa8muXo02mDTFexZzsis"
ENV CREDS_PATH="./creds.json"
ENV FILENAME="tweets"
CMD ["python", "run.py"]